### ISSUE TITLE
Crash when generating previews

### ISSUE THREAD

**Issue by Lunatory** [PayneZA/OutfitManager#12]
Possibly related to the glamourer changes, Dalamud throws a crash right after the first outfit change when generating previews. Log:

```
Unhandled native exception occurred at ffxiv_dx11.exe+1802992	(GFSDK_SSAO_CreateContext_D3D11+0x17AE52)
Code: C0000005
Dump at: C:\Users\user\AppData\Roaming\XIVLauncher\dalamud_appcrash_20231114_102547_527_12400.dmp
Time: 2023-11-14 10:25:48.4567256 EST

   at Penumbra.Interop.Services.GameEventManager.WeaponReloadDetour(IntPtr a1, UInt32 a2, IntPtr a3, Byte a4, Byte a5, Byte a6, Byte a7)
   at Glamourer.Interop.WeaponService.LoadWeapon(Actor character, EquipSlot slot, CharacterWeapon weapon)
   at Glamourer.State.StateApplier.ChangeMainhand(ActorData data, EquipItem weapon, StainId stain)
   at Glamourer.State.StateManager.ApplyAll(ActorState state, Boolean redraw, Boolean withLock)
   at Glamourer.State.StateManager.ApplyDesign(DesignBase design, ActorState state, Source source, UInt32 key)
   at Glamourer.Services.CommandService.Apply(String arguments)
   at Glamourer.Services.CommandService.OnGlamour(String command, String arguments)
   at Dalamud.Game.Command.CommandManager.DispatchCommand(String command, String argument, CommandInfo info)
   at Dalamud.Game.Command.CommandManager.ProcessCommand(String content)
   at Dalamud.Game.Command.CommandManagerPluginScoped.ProcessCommand(String content)
   at OutfitManager.Handlers.OutfitHandler.EquipOutfit(String outfitName, String tag, Boolean gearset, Boolean ignoreCollection)
   at OutfitManager.Services.OutfitCaptureService.CaptureOutfits(Boolean replaceExisting, Boolean cropToVerical)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetResult()
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF7C37B2992
Parameters: 0, 58
Call Stack
{
  [0]	ffxiv_dx11.exe+1802992	(GFSDK_SSAO_CreateContext_D3D11+0x17AE52)
  [1]	ffxiv_dx11.exe+1802992	(GFSDK_SSAO_CreateContext_D3D11+0x17AE52)
  [2]	ffxiv_dx11.exe+17C269F	(GFSDK_SSAO_CreateContext_D3D11+0x13AB5F)
  [3]	ffxiv_dx11.exe+17C31B4	(GFSDK_SSAO_CreateContext_D3D11+0x13B674)
  [4]	ffxiv_dx11.exe+337DF5
  [5]	ffxiv_dx11.exe+348C64
  [6]	ffxiv_dx11.exe+33702F
  [7]	ffxiv_dx11.exe+348CD4
  [8]	ffxiv_dx11.exe+13CCDB4
  [9]	ffxiv_dx11.exe+13C9EAA
  [10]	ffxiv_dx11.exe+13CDE85
  [11]	ffxiv_dx11.exe+143D850
  [12]	ffxiv_dx11.exe+139C238
  [13]	ffxiv_dx11.exe+1317D9F
  [14]	7FF93D6A83AE
}

Registers
{
  RAX:	0
  RBX:	8
  RCX:	1D
  RDX:	1F7933F56D0 [1F79523D0A0]
  R8:	8
  R9:	1
  R10:	1F79523CD80 [ffxiv_dx11.exe+19E5818	(GFSDK_SSAO_CreateContext_D3D11+0x35DCD8)]
  R11:	0
  R12:	1
  R13:	0
  R14:	1F79523D0A0 [ffxiv_dx11.exe+19E5858	(GFSDK_SSAO_CreateContext_D3D11+0x35DD18)]
  R15:	1F784BD71A0
  RSI:	0
  RDI:	1F7933F56D0 [1F79523D0A0]
  RBP:	8
  RSP:	590B4FE590 [1F79523D090]
  RIP:	ffxiv_dx11.exe+1802992	(GFSDK_SSAO_CreateContext_D3D11+0x17AE52)
}

Stack
{
  [RSP+0]	1F79523D090 [ffxiv_dx11.exe+19E5838	(GFSDK_SSAO_CreateContext_D3D11+0x35DCF8)]
  [RSP+8]	0
  [RSP+10]	3
  [RSP+18]	ffxiv_dx11.exe+337E71 [1EF834808C38348]
  [RSP+20]	1
  [RSP+28]	ffxiv_dx11.exe+17C269F	(GFSDK_SSAO_CreateContext_D3D11+0x13AB5F)
  [RSP+30]	1F79522BFE0 [ffxiv_dx11.exe+1D396E8	(GFSDK_SSAO_CreateContext_D3D11+0x6B1BA8)]
  [RSP+38]	1F791D2F140 [1F791D2F140]
  [RSP+40]	1F7932B7BF0 [ffxiv_dx11.exe+19E58C8	(GFSDK_SSAO_CreateContext_D3D11+0x35DD88)]
  [RSP+48]	ffxiv_dx11.exe+33F87B [245C8B4801084B83]
  [RSP+50]	1F79522BFE0 [ffxiv_dx11.exe+1D396E8	(GFSDK_SSAO_CreateContext_D3D11+0x6B1BA8)]
  [RSP+58]	ffxiv_dx11.exe+17C31B4	(GFSDK_SSAO_CreateContext_D3D11+0x13B674)
  [RSP+60]	2
  [RSP+68]	1F79523D090 [ffxiv_dx11.exe+19E5838	(GFSDK_SSAO_CreateContext_D3D11+0x35DCF8)]
  [RSP+70]	1F79523D090 [ffxiv_dx11.exe+19E5838	(GFSDK_SSAO_CreateContext_D3D11+0x35DCF8)]
  [RSP+78]	ffxiv_dx11.exe+349966 [80249C8B48]
}

Modules
{
  00400000	C:\Windows\SYSTEM32\XInput1_3.dll	Microsoft Common Controller API v9.18.944.0
  77AE0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\FASMX64.dll	<no description> v1.73.16.0
  180000000	C:\Users\user\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.8.0.6\runtimes\win-x64\native\FreeImage.dll	FreeImage library v3.18.0.0
  1F782350000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.dll	Dalamud v9.0.0.11
  1F7B77D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.dll	System.Reflection file=v7.0.22.51805 prod=v7.0.0.0
  1F7BAB50000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.dll	System.Runtime file=v7.0.22.51805 prod=v7.0.0.0
  1F7BAB90000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Common.dll	Dalamud.Common v1.0.0.0
  1F7BABA0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Thread.dll	System.Threading.Thread file=v7.0.22.51805 prod=v7.0.0.0
  1F7BABB0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Xml.ReaderWriter.dll	System.Xml.ReaderWriter file=v7.0.22.51805 prod=v7.0.0.0
  1F7BABC0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Emit.ILGeneration.dll	System.Reflection.Emit.ILGeneration file=v7.0.22.51805 prod=v7.0.0.0
  1F7BABD0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Emit.Lightweight.dll	System.Reflection.Emit.Lightweight file=v7.0.22.51805 prod=v7.0.0.0
  1F7BABE0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Primitives.dll	System.Reflection.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  1F7BABF0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Serilog.dll	Serilog v2.11.0.0
  1F7BAC20000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Reloaded.Hooks.dll	Reloaded.Hooks v4.2.0.0
  1F7BAC50000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Newtonsoft.Json.dll	Json.NET .NET 6.0 file=v13.0.2.27524 prod=v13.0.2.0
  1F7BAD10000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Numerics.Vectors.dll	System.Numerics.Vectors file=v7.0.22.51805 prod=v7.0.0.0
  1F7BAD20000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Serilog.Sinks.Async.dll	Serilog.Sinks.Async v1.5.0.0
  1F7BAD30000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\netstandard.dll	netstandard file=v7.0.22.51805 prod=v7.0.0.0
  2384F810000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\FFXIVClientStructs.dll	FFXIVClientStructs v1.0.0.2997
  2384F960000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Serilog.Sinks.Console.dll	Serilog.Sinks.Console v4.0.1.0
  2384F970000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Serilog.Sinks.File.dll	Serilog.Sinks.File v5.0.0.0
  2384F980000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.FileSystem.dll	System.IO.FileSystem file=v7.0.22.51805 prod=v7.0.0.0
  2384F990000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Text.Encoding.Extensions.dll	System.Text.Encoding.Extensions file=v7.0.22.51805 prod=v7.0.0.0
  2384F9A0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SQLite-net.dll	SQLite-net Official .NET Standard Library v1.8.116.0
  2384F9C0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SQLitePCLRaw.core.dll	SQLitePCLRaw.core file=v2.0.4.976 prod=v2.0.4.0
  2384F9E0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SQLitePCLRaw.batteries_v2.dll	SQLitePCLRaw.batteries_v2 file=v2.0.4.976 prod=v2.0.4.0
  2384F9F0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SQLitePCLRaw.provider.dynamic_cdecl.dll	SQLitePCLRaw.provider.dynamic_cdecl file=v2.0.4.976 prod=v2.0.4.0
  2384FA10000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SQLitePCLRaw.nativelibrary.dll	SQLitePCLRaw.nativelibrary file=v2.0.4.976 prod=v2.0.4.0
  2384FA20000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\ImGui.NET.dll	ImGui.NET file=v1.82.0.0 prod=v1.0.0.0
  2384FAB0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Reloaded.Memory.Buffers.dll	Reloaded.Memory.Buffers v2.0.0.0
  2384FAC0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\PInvoke.Kernel32.dll	PInvoke.Kernel32 file=v0.7.104.53878 prod=v0.7.104.0
  2384FAE0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\Microsoft.Win32.Primitives.dll	Microsoft.Win32.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  2384FAF0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.dll	Lumina v3.15.2.0
  2384FB40000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Loader.dll	System.Runtime.Loader file=v7.0.22.51805 prod=v7.0.0.0
  2384FB50000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Iced.dll	Iced v1.17.0.0
  2384FD20000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\CheapLoc.dll	CheapLoc file=v1.1.8.0 prod=v1.0.0.0
  2384FD30000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.Tracing.dll	System.Diagnostics.Tracing file=v7.0.22.51805 prod=v7.0.0.0
  2384FD40000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Reloaded.Hooks.Definitions.dll	Reloaded.Hooks.Definitions v1.14.0.0
  2384FD60000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.CompilerServices.Unsafe.dll	System.Runtime.CompilerServices.Unsafe file=v7.0.22.51805 prod=v7.0.0.0
  2384FD70000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Reloaded.Memory.dll	Reloaded.Memory v7.0.0.0
  2384FD90000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Reloaded.Assembler.dll	Reloaded.Assembler v1.0.14.0
  2384FDA0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll	Lumina.Excel v6.5.2.0
  23850110000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\PInvoke.User32.dll	PInvoke.User32 file=v0.7.104.53878 prod=v0.7.104.0
  23850130000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\System.Reactive.dll	System.Reactive file=v5.0.0.1 prod=v5.0.0.0
  238502A0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\PInvoke.Windows.Core.dll	PInvoke.Windows.Core file=v0.7.104.53878 prod=v0.7.104.0
  238502F0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.ThreadPool.dll	System.Threading.ThreadPool file=v7.0.22.51805 prod=v7.0.0.0
  23850300000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\MonoMod.RuntimeDetour.dll	MonoMod.RuntimeDetour file=v23.1.2.0 prod=v0.0.0.0
  23850320000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\MonoMod.Utils.dll	MonoMod.Utils file=v23.1.2.0 prod=v0.0.0.0
  23850370000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\MonoMod.Core.dll	MonoMod.Core file=v23.1.2.0 prod=v0.0.0.0
  238503B0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\MonoMod.ILHelpers.dll	<no information available>
  238503C0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\MonoMod.Backports.dll	MonoMod.Backports file=v23.1.2.0 prod=v0.0.0.0
  238503D0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Mono.Cecil.dll	Mono.Cecil v0.11.4.0
  23850430000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\mscorlib.dll	mscorlib file=v7.0.22.51805 prod=v7.0.0.0
  23850450000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Overlapped.dll	System.Threading.Overlapped file=v7.0.22.51805 prod=v7.0.0.0
  23850460000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\ImGuiScene.dll	ImGuiScene v1.0.0.0
  2387A8D0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SharpDX.DXGI.dll	SharpDX.DXGI v4.2.0.0
  2387E400000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SharpDX.Mathematics.dll	SharpDX.Mathematics v4.2.0.0
  2387E5B0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SharpDX.dll	SharpDX v4.2.0.0
  2387E600000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\SharpDX.Direct3D11.dll	SharpDX.Direct3D11 v4.2.0.0
  2387E650000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\StbiSharp.dll	STBI C# wrapper v1.0.13.0
  2387E670000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Extensions.dll	System.Runtime.Extensions file=v7.0.22.51805 prod=v7.0.0.0
  2388AD40000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.InteropServices.RuntimeInformation.dll	System.Runtime.InteropServices.RuntimeInformation file=v7.0.22.51805 prod=v7.0.0.0
  2388AD50000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Extensions.dll	System.Reflection.Extensions file=v7.0.22.51805 prod=v7.0.0.0
  2388AD60000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.AppContext.dll	System.AppContext file=v7.0.22.51805 prod=v7.0.0.0
  2388AD90000	C:\Users\user\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.8.0.6\runtimes\win-x64\native\nvtt.dll	NVIDIA Texture Tools Dynamic Link Library v2.1.0.0
  23894750000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.dll	System.IO file=v7.0.22.51805 prod=v7.0.0.0
  23895770000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Text.Encoding.dll	System.Text.Encoding file=v7.0.22.51805 prod=v7.0.0.0
  23895780000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Globalization.dll	System.Globalization file=v7.0.22.51805 prod=v7.0.0.0
  238A5C30000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Emit.dll	System.Reflection.Emit file=v7.0.22.51805 prod=v7.0.0.0
  238CF360000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Security.Cryptography.X509Certificates.dll	System.Security.Cryptography.X509Certificates file=v7.0.22.51805 prod=v7.0.0.0
  238CFA40000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Tasks.dll	System.Threading.Tasks file=v7.0.22.51805 prod=v7.0.0.0
  238CFA50000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Buffers.dll	System.Buffers file=v7.0.22.51805 prod=v7.0.0.0
  238D9560000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.dll	System file=v7.0.22.51805 prod=v7.0.0.0
  238D95B0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Core.dll	System.Core file=v7.0.22.51805 prod=v7.0.0.0
  238DAAF0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Intrinsics.dll	System.Runtime.Intrinsics file=v7.0.22.51805 prod=v7.0.0.0
  238DD010000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Xml.XDocument.dll	System.Xml.XDocument file=v7.0.22.51805 prod=v7.0.0.0
  7FF7C1FB0000	C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxiv_dx11.exe	FINAL FANTASY XIV v1.0.0.0
  7FF9977C0000	C:\Windows\System32\p9np.dll	Plan 9 Network Provider file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF998CF0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Private.Xml.dll	System.Private.Xml file=v7.0.22.51805 prod=v0.0.0.0
  7FF999500000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Data.Common.dll	System.Data.Common file=v7.0.22.51805 prod=v7.0.0.0
  7FF9997E0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ComponentModel.TypeConverter.dll	System.ComponentModel.TypeConverter file=v7.0.22.51805 prod=v7.0.0.0
  7FF9998A0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Linq.Expressions.dll	System.Linq.Expressions file=v7.0.22.51805 prod=v7.0.0.0
  7FF999C50000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.TraceSource.dll	System.Diagnostics.TraceSource file=v7.0.22.51805 prod=v7.0.0.0
  7FF999C80000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Numerics.dll	System.Runtime.Numerics file=v7.0.22.51805 prod=v7.0.0.0
  7FF999CD0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Serialization.Formatters.dll	System.Runtime.Serialization.Formatters file=v7.0.22.51805 prod=v7.0.0.0
  7FF999D20000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Boot.dll	<no information available>
  7FF999ED0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\clrjit.dll	Microsoft .NET Runtime Just-In-Time Compiler v7.0.22.51805
  7FF99A050000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Private.CoreLib.dll	System.Private.CoreLib file=v7.0.22.51805 prod=v7.0.0.0
  7FF99AB70000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\coreclr.dll	Microsoft .NET Runtime v7.0.22.51805
  7FF99B800000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Text.RegularExpressions.dll	System.Text.RegularExpressions file=v7.0.22.51805 prod=v7.0.0.0
  7FF9AD000000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Linq.dll	System.Linq file=v7.0.22.51805 prod=v7.0.0.0
  7FF9AD080000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\hostpolicy.dll	.NET Host Policy - 7.0.0 v7.0.22.51805
  7FF9B38E0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.WindowsDesktop.App\7.0.0\System.Windows.Forms.dll	System.Windows.Forms file=v7.0.22.51807 prod=v0.0.0.0
  7FF9B45A0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\runtimes\win-x64\native\cimplot.dll	<no information available>
  7FF9B4D10000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\host\fxr\7.0.0\hostfxr.dll	.NET Host Resolver - 7.0.0 v7.0.22.51805
  7FF9B51D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Linq.Parallel.dll	System.Linq.Parallel file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B6280000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Transactions.Local.dll	System.Transactions.Local file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B64B0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.NetworkInformation.dll	System.Net.NetworkInformation file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B6930000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Collections.Concurrent.dll	System.Collections.Concurrent file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B6F40000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.Process.dll	System.Diagnostics.Process file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B71E0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Console.dll	System.Console file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B7220000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Private.Xml.Linq.dll	System.Private.Xml.Linq file=v7.0.22.51805 prod=v0.0.0.0
  7FF9B8C30000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Memory.dll	System.Memory file=v7.0.22.51805 prod=v7.0.0.0
  7FF9B90B0000	C:\Windows\System32\davclnt.dll	Web DAV Client DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9B90D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Private.Uri.dll	System.Private.Uri file=v7.0.22.51805 prod=v0.0.0.0
  7FF9B9540000	C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\dxgi.dll	GShade 4.2.2 based on crosire's ReShade post-processing injector for 64-bit v5.8.0.1
  7FF9B9A40000	C:\Users\user\AppData\Local\Temp\oecjfuw1.3hu\SQLite.Interop.dll	System.Data.SQLite Interop Assembly v1.0.117.0
  7FF9B9C00000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\Microsoft.DiaSymReader.Native.amd64.dll	Dia based SymReader v14.28.29715.1
  7FF9B9DD0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.WindowsDesktop.App\7.0.0\System.Windows.Forms.Primitives.dll	System.Windows.Forms.Primitives file=v7.0.22.51807 prod=v0.0.0.0
  7FF9B9EC0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\runtimes\win-x64\native\cimguizmo.dll	<no information available>
  7FF9BA0A0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\runtimes\win-x64\native\cimgui.dll	<no information available>
  7FF9BA2A0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.HttpListener.dll	System.Net.HttpListener file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BA350000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\Microsoft.CSharp.dll	Microsoft.CSharp file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BA450000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Collections.Immutable.dll	System.Collections.Immutable file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BA500000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Security.Cryptography.dll	System.Security.Cryptography file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BA6E0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Http.dll	System.Net.Http file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BA890000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Text.Json.dll	System.Text.Json file=v7.0.22.51805 prod=v7.0.0.0
  7FF9BAA00000	C:\Users\user\AppData\Local\Temp\Machina.FFXIV\deucalion-0.9.3.dll	deucalion v0.9.3.0
  7FF9BAFA0000	C:\Windows\SYSTEM32\WMVCore.DLL	Windows Media Playback/Authoring DLL v12.0.22621.2506
  7FF9BBC10000	C:\Windows\System32\ntlanman.dll	Microsoft  Lan Manager file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9C3E20000	C:\Windows\SYSTEM32\VCRUNTIME140_CLR0400.dll	Microsoft  C Runtime Library v14.32.31326.0
  7FF9C3E40000	C:\Windows\SYSTEM32\ucrtbase_clr0400.dll	Microsoft  C Runtime Library v14.32.31326.0
  7FF9C4960000	C:\Windows\SYSTEM32\mscoree.dll	Microsoft .NET Runtime Execution Engine file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9E6240000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.WebSockets.dll	System.Net.WebSockets file=v7.0.22.51805 prod=v7.0.0.0
  7FF9E6270000	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll	WMINet_Utils.dll file=v4.8.9032.0 prod=v4.0.30319.0
  7FF9E62A0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Security.AccessControl.dll	System.Security.AccessControl file=v7.0.22.51805 prod=v7.0.0.0
  7FF9E6990000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.Pipes.dll	System.IO.Pipes file=v7.0.22.51805 prod=v7.0.0.0
  7FF9E6A80000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ComponentModel.Annotations.dll	System.ComponentModel.Annotations file=v7.0.22.51805 prod=v7.0.0.0
  7FF9E6B80000	C:\Windows\SYSTEM32\icu.dll	ICU Combined Library v68.2.0.10
  7FF9E7930000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Collections.dll	System.Collections file=v7.0.22.51805 prod=v7.0.0.0
  7FF9ECBD0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\Microsoft.Win32.Registry.dll	Microsoft.Win32.Registry file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EDA50000	C:\Windows\SYSTEM32\ondemandconnroutehelper.dll	On Demand Connctiond Route Helper file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9EE3D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ObjectModel.dll	System.ObjectModel file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EE3F0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Channels.dll	System.Threading.Channels file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EE410000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Reflection.Metadata.dll	System.Reflection.Metadata file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EEA30000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Collections.Specialized.dll	System.Collections.Specialized file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EEA80000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Tasks.Dataflow.dll	System.Threading.Tasks.Dataflow file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EEB80000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.WebClient.dll	System.Net.WebClient file=v7.0.22.51805 prod=v7.0.0.0
  7FF9EF280000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\nethost.dll	.NET Core Component Host v3.0.19.46305
  7FF9F0340000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Ping.dll	System.Net.Ping file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F0360000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\runtimes\win-x64\native\stbi.dll	<no information available>
  7FF9F03A0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Requests.dll	System.Net.Requests file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F0540000	C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\XInputXIV3.dll	<no information available>
  7FF9F12B0000	C:\Windows\SYSTEM32\LINKINFO.dll	Windows Volume Tracking file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9F1A00000	C:\Windows\SYSTEM32\ntshrui.dll	Shell extensions for sharing file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9F2C60000	C:\Windows\system32\dataexchange.dll	Data exchange file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9F35D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ComponentModel.Primitives.dll	System.ComponentModel.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F35F0000	C:\Users\user\AppData\Local\Temp\Costura\EA7B554EE10BEAD803E24B5B4007EE7E\64\stbi.dll	<no information available>
  7FF9F3610000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.Compression.Brotli.dll	System.IO.Compression.Brotli file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F3630000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.Compression.Native.dll	.NET Runtime v7.0.22.51805
  7FF9F3700000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.Compression.dll	System.IO.Compression file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F4FA0000	C:\Windows\SYSTEM32\WININET.dll	Internet Extensions for Win32 v11.0.22621.2506
  7FF9F85E0000	C:\Windows\system32\nvspcap64.dll	NVIDIA Game Proxy v3.27.0.112
  7FF9F88C0000	C:\Windows\SYSTEM32\MPR.dll	Multiple Provider Router DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9F8940000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Formats.Asn1.dll	System.Formats.Asn1 file=v7.0.22.51805 prod=v7.0.0.0
  7FF9F9310000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.WebSockets.Client.dll	System.Net.WebSockets.Client file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FAA70000	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll	User Experience Controls Library file=v5.82.22621.2506 prod=v10.0.22621.2506
  7FF9FC320000	C:\Windows\SYSTEM32\XInput1_4.dll	Microsoft Common Controller API file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9FC870000	C:\Windows\System32\deviceaccess.dll	Device Broker And Policy COM Server file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9FDA40000	C:\Windows\SYSTEM32\cscapi.dll	Offline Files Win32 API file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9FDAF0000	C:\Windows\SYSTEM32\VCRUNTIME140.dll	Microsoft  C Runtime Library v14.38.32919.0
  7FF9FDB10000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.WebHeaderCollection.dll	System.Net.WebHeaderCollection file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FDC80000	C:\Windows\System32\drprov.dll	Microsoft Remote Desktop Session Host Server Network Provider file=v6.2.22621.1 prod=v10.0.22621.1
  7FF9FDD20000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ComponentModel.EventBasedAsync.dll	System.ComponentModel.EventBasedAsync file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FDE80000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.Compression.ZipFile.dll	System.IO.Compression.ZipFile file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FDE90000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.IO.MemoryMappedFiles.dll	System.IO.MemoryMappedFiles file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FDEB0000	C:\Users\user\AppData\Roaming\XIVLauncher\addon\Hooks\dev\runtimes\win-x64\native\e_sqlite3.dll	<no information available>
  7FF9FE0D0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.StackTrace.dll	System.Diagnostics.StackTrace file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FE1F0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.ComponentModel.dll	System.ComponentModel file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FE340000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Security.Principal.Windows.dll	System.Security.Principal.Windows file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FE4F0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.dll	System.Threading file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FED50000	C:\Windows\system32\ncryptsslp.dll	Microsoft SChannel Provider file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9FF370000	C:\Windows\System32\Windows.StateRepositoryPS.dll	Windows StateRepository Proxy/Stub Server file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FF9FFCA0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.Serialization.Primitives.dll	System.Runtime.Serialization.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FFD00000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Security.Claims.dll	System.Security.Claims file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FFD20000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.NameResolution.dll	System.Net.NameResolution file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FFD40000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.DiagnosticSource.dll	System.Diagnostics.DiagnosticSource file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FFDA0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Sockets.dll	System.Net.Sockets file=v7.0.22.51805 prod=v7.0.0.0
  7FF9FFED0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Runtime.InteropServices.dll	System.Runtime.InteropServices file=v7.0.22.51805 prod=v7.0.0.0
  7FFA002B0000	C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23100.2009-0\MPCLIENT.DLL	Client Interface v4.18.23100.2009
  7FFA00FC0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Primitives.dll	System.Net.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  7FFA01000000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Text.Encodings.Web.dll	System.Text.Encodings.Web file=v7.0.22.51805 prod=v7.0.0.0
  7FFA01020000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.Security.dll	System.Net.Security file=v7.0.22.51805 prod=v7.0.0.0
  7FFA01180000	C:\Windows\SYSTEM32\WMASF.DLL	Windows Media ASF DLL v12.0.22621.1
  7FFA01A10000	C:\Windows\SYSTEM32\xinput9_1_0.dll	XNA Common Controller file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA01A20000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Threading.Tasks.Parallel.dll	System.Threading.Tasks.Parallel file=v7.0.22.51805 prod=v7.0.0.0
  7FFA01B00000	C:\Windows\system32\wshunix.dll	AF_UNIX Winsock2 Helper DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA02E20000	C:\Windows\SYSTEM32\AUDIOSES.DLL	Audio Session file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA032C0000	C:\Windows\SYSTEM32\httpapi.dll	HTTP Protocol Stack API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA03580000	C:\Windows\SYSTEM32\textinputframework.dll	"TextInputFramework.DYNLINK" file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA036D0000	C:\Windows\SYSTEM32\inputhost.dll	InputHost file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA04140000	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\Display.NvContainer\MessageBus.dll	NVIDIA Message Bus file=v1.22.2758.1620 prod=v1.22.0.0
  7FFA04880000	C:\Windows\SYSTEM32\amsi.dll	Anti-Malware Scan Interface file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA04B80000	C:\Windows\SYSTEM32\nvapi64.dll	NVIDIA NVAPI Library, Version 546.01  v31.0.15.4601
  7FFA053A0000	C:\Windows\system32\wbem\wmiutils.dll	WMI file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA053D0000	C:\Windows\system32\wbem\wbemsvc.dll	WMI file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA053F0000	C:\Windows\system32\wbem\fastprox.dll	WMI Custom Marshaller file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA07360000	C:\Windows\SYSTEM32\windows.staterepositoryclient.dll	Windows StateRepository Client API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA07540000	C:\Windows\SYSTEM32\windows.staterepositorycore.dll	Windows StateRepository API Core file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA07590000	C:\Windows\System32\Windows.System.Launcher.dll	Windows.System.Launcher file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA07720000	C:\Windows\SYSTEM32\WINMM.dll	MCI API DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA07AB0000	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\nvwgf2umx.dll	NVIDIA D3D10 Driver, Version 546.01  v31.0.15.4601
  7FFA0CEC0000	C:\Windows\SYSTEM32\wbemcomn.dll	WMI file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA0CF40000	C:\Windows\system32\wbem\wbemprox.dll	WMI file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA0D670000	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\nvgpucomp64.dll	NVIDIA GPU Compiler Driver, Version 546.01  v31.0.15.4601
  7FFA0FE90000	C:\Windows\System32\MMDevApi.dll	MMDevice API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA10020000	C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23100.2009-0\MpOav.dll	IOfficeAntiVirus Module v4.18.23100.2009
  7FFA10100000	C:\Windows\System32\rasadhlp.dll	Remote Access AutoDial Helper file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA10B40000	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\nvldumdx.dll	NVIDIA Driver Loader, Version 546.01  v31.0.15.4601
  7FFA10FE0000	C:\Windows\SYSTEM32\DINPUT8.dll	Microsoft DirectInput file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA11030000	C:\Windows\SYSTEM32\dbgcore.DLL	Windows Core Debugging Helpers file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA110E0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Diagnostics.FileVersionInfo.dll	System.Diagnostics.FileVersionInfo file=v7.0.22.51805 prod=v7.0.0.0
  7FFA110F0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Collections.NonGeneric.dll	System.Collections.NonGeneric file=v7.0.22.51805 prod=v7.0.0.0
  7FFA11110000	C:\Windows\SYSTEM32\iertutil.dll	Run time utility for Internet Explorer v11.0.22621.2506
  7FFA113F0000	C:\Windows\SYSTEM32\srvcli.dll	Server Service Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA11570000	C:\Windows\SYSTEM32\urlmon.dll	OLE32 Extensions for Win32 v11.0.22621.2506
  7FFA119C0000	C:\Windows\SYSTEM32\drvstore.dll	Driver Store API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA11B20000	C:\Windows\system32\twinapi.appcore.dll	twinapi.appcore file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA11DB0000	C:\Windows\System32\fwpuclnt.dll	FWP/IPsec User-Mode API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA11E90000	C:\Windows\SYSTEM32\cryptnet.dll	Crypto Network Related API file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA11ED0000	C:\Windows\SYSTEM32\VERSION.dll	Version Checking and File Installation Libraries file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA12A50000	C:\Windows\System32\wkscli.dll	Workstation Service Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA12A70000	C:\Windows\SYSTEM32\CoreUIComponents.dll	Microsoft Core UI Components Dll file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA131A0000	C:\Windows\SYSTEM32\dhcpcsvc.DLL	DHCP Client Service file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA131C0000	C:\Windows\SYSTEM32\dhcpcsvc6.DLL	DHCPv6 Client file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA144B0000	C:\Windows\SYSTEM32\directxdatabasehelper.dll	DirectXDatabaseHelper file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA14500000	C:\Windows\SYSTEM32\WINHTTP.dll	Windows HTTP Services file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA147A0000	C:\Windows\system32\wshbth.dll	Windows Sockets Helper DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA155C0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Drawing.Primitives.dll	System.Drawing.Primitives file=v7.0.22.51805 prod=v7.0.0.0
  7FFA15630000	C:\Windows\system32\nlansp_c.dll	NLA Namespace Service Provider DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA15660000	C:\Windows\System32\winrnr.dll	LDAP RnR Provider DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA15A30000	C:\Windows\SYSTEM32\VCRUNTIME140_1_CLR0400.dll	Microsoft  C Runtime Library v14.32.31326.0
  7FFA15DB0000	C:\Windows\SYSTEM32\D3DCOMPILER_47.dll	Direct3D HLSL Compiler file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA16B30000	C:\Windows\SYSTEM32\d3d11.dll	Direct3D 11 Runtime file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA17A10000	C:\Windows\SYSTEM32\CoreMessaging.dll	Microsoft CoreMessaging Dll file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA17D20000	C:\Windows\system32\pnrpnsp.dll	PNRP Name Space Provider file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA17D40000	C:\Windows\system32\napinsp.dll	E-mail Naming Shim Provider file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA17DA0000	C:\Users\user\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\7.0.0\System.Net.ServicePoint.dll	System.Net.ServicePoint file=v7.0.22.51805 prod=v7.0.0.0
  7FFA17E00000	C:\Windows\SYSTEM32\msvcp110_win.dll	Microsoft  STL110 C++ Runtime Library file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA17EA0000	C:\Windows\SYSTEM32\PROPSYS.dll	Microsoft Property System v7.0.22621.2506
  7FFA17FB0000	C:\Windows\SYSTEM32\policymanager.dll	Policy Manager DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA183B0000	C:\Windows\SYSTEM32\apphelp.dll	Application Compatibility Client Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA18650000	C:\Windows\system32\uxtheme.dll	Microsoft UxTheme Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA18770000	C:\Windows\SYSTEM32\WINNSI.DLL	Network Store Information RPC interface file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA187C0000	C:\Windows\SYSTEM32\dxcore.dll	DXCore file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA18820000	C:\Windows\system32\dxgi.dll	DirectX Graphics Infrastructure file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA18930000	C:\Windows\SYSTEM32\dwmapi.dll	Microsoft Desktop Window Manager API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA18D20000	C:\Windows\SYSTEM32\resourcepolicyclient.dll	Resource Policy Client file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA18E30000	C:\Windows\SYSTEM32\dbghelp.dll	Windows Image Helper file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA19450000	C:\Windows\SYSTEM32\wintypes.dll	Windows Base Types DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA19590000	C:\Windows\SYSTEM32\windows.storage.dll	Microsoft WinRT Storage API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA19E90000	C:\Windows\SYSTEM32\HID.DLL	Hid User Library file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1A0E0000	C:\Windows\System32\netutils.dll	Net Win32 API Helpers DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1A0F0000	C:\Windows\SYSTEM32\IPHLPAPI.DLL	IP Helper API file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1A160000	C:\Windows\SYSTEM32\DNSAPI.dll	DNS Client API DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1A4C0000	C:\Windows\system32\schannel.DLL	TLS / SSL Security Provider file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1A5D0000	C:\Windows\system32\rsaenh.dll	Microsoft Enhanced Cryptographic Provider file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1A670000	C:\Windows\SYSTEM32\kernel.appcore.dll	AppModel API Host file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1A690000	C:\Windows\SYSTEM32\ntmarta.dll	Windows NT MARTA provider file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1A8D0000	C:\Windows\SYSTEM32\sspicli.dll	Security Support Provider Interface file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AAF0000	C:\Windows\system32\mswsock.dll	Microsoft Windows Sockets 2.0 Service Provider file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AB80000	C:\Windows\SYSTEM32\gpapi.dll	Group Policy Client API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1ABE0000	C:\Windows\SYSTEM32\userenv.dll	Userenv file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AD40000	C:\Windows\SYSTEM32\CRYPTSP.dll	Cryptographic Service Provider API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AD60000	C:\Windows\SYSTEM32\CRYPTBASE.DLL	Base cryptographic API DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1ADF0000	C:\Windows\SYSTEM32\wldp.dll	Windows Lockdown Policy file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AEA0000	C:\Windows\SYSTEM32\NTASN1.dll	Microsoft ASN.1 API file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1AEE0000	C:\Windows\SYSTEM32\ncrypt.dll	Windows NCrypt Router file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1AF10000	C:\Windows\SYSTEM32\bcrypt.dll	Windows Cryptographic Primitives Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B220000	C:\Windows\SYSTEM32\DEVOBJ.dll	Device Information Set DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B250000	C:\Windows\SYSTEM32\cfgmgr32.dll	Configuration Manager DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B2A0000	C:\Windows\SYSTEM32\MSASN1.dll	ASN.1 Runtime APIs file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B2E0000	C:\Windows\SYSTEM32\DPAPI.DLL	Data Protection API file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1B3F0000	C:\Windows\SYSTEM32\sxs.dll	Fusion 2.5 file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B4A0000	C:\Windows\System32\WINSTA.dll	Winstation Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B520000	C:\Windows\SYSTEM32\UMPDC.dll	User Mode Power Dependency Coordinator file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1B540000	C:\Windows\SYSTEM32\powrprof.dll	Power Profile Helper DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B5A0000	C:\Windows\SYSTEM32\profapi.dll	User Profile Basic API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B670000	C:\Windows\System32\ucrtbase.dll	Microsoft  C Runtime Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1B850000	C:\Windows\System32\KERNELBASE.dll	Windows NT BASE API Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BC00000	C:\Windows\System32\gdi32full.dll	GDI Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BD20000	C:\Windows\System32\bcryptPrimitives.dll	Windows Cryptographic Primitives Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BDA0000	C:\Windows\System32\win32u.dll	Win32u file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BDD0000	C:\Windows\System32\msvcp_win.dll	Microsoft  C Runtime Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BE70000	C:\Windows\System32\WINTRUST.dll	Microsoft Trust Verification APIs file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1BEE0000	C:\Windows\System32\CRYPT32.dll	Crypto API32 file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C050000	C:\Windows\System32\RPCRT4.dll	Remote Procedure Call Runtime file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C170000	C:\Windows\System32\GDI32.dll	GDI Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C1A0000	C:\Windows\System32\clbcatq.dll	COM+ Configuration Catalog file=v2001.12.10941.16384 prod=v10.0.22621.2506
  7FFA1C250000	C:\Windows\System32\OLEAUT32.dll	OLEAUT32.DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C330000	C:\Windows\System32\coml2.dll	Microsoft COM for Windows file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C3B0000	C:\Windows\System32\shlwapi.dll	Shell Light-weight Utility Library file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C460000	C:\Windows\System32\combase.dll	Microsoft COM for Windows file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1C810000	C:\Windows\System32\SETUPAPI.dll	Windows Setup API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1CC90000	C:\Windows\System32\NSI.dll	NSI User-mode interface DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1CCA0000	C:\Windows\System32\msvcrt.dll	Windows NT CRT DLL file=v7.0.22621.2506 prod=v10.0.22621.2506
  7FFA1CD50000	C:\Windows\System32\KERNEL32.DLL	Windows NT BASE API Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1CE20000	C:\Windows\System32\ADVAPI32.dll	Advanced Windows 32 Base API file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1CFE0000	C:\Windows\System32\imagehlp.dll	Windows NT Image Helper file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1D000000	C:\Windows\System32\SHCORE.dll	SHCORE file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1D100000	C:\Windows\System32\sechost.dll	Host for SCM/SDDL/LSA Lookup APIs file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1D1B0000	C:\Windows\System32\PSAPI.DLL	Process Status Helper file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1D260000	C:\Windows\System32\USER32.dll	Multi-User Windows USER API Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1D6A0000	C:\Windows\System32\MSCTF.dll	MSCTF Server DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1D7F0000	C:\Windows\System32\WS2_32.dll	Windows Socket 2.0 32-Bit DLL file=v6.2.22621.1 prod=v10.0.22621.1
  7FFA1D870000	C:\Windows\System32\SHELL32.dll	Windows Shell Common Dll file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1E0D0000	C:\Windows\System32\IMM32.dll	Multi-User Windows IMM32 API Client DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1E110000	C:\Windows\System32\ole32.dll	Microsoft OLE for Windows file=v6.2.22621.2506 prod=v10.0.22621.2506
  7FFA1E2F0000	C:\Windows\SYSTEM32\ntdll.dll	NT Layer DLL file=v6.2.22621.2506 prod=v10.0.22621.2506
}
```

**Comment by PayneZA** [comment]
Hello

Thankyou for the report, problem should be fixed now, needed to update for penumbra api.

Can you confirm working for you after updating to 0.0.6.5

**Comment by NjalTheKnut** [comment]
Hi, I am also experiencing this, and I believe I have the latest version.

**Comment by Lunatory** [comment]
> Hello
> 
> Thankyou for the report, problem should be fixed now, needed to update for penumbra api.
> 
> Can you confirm working for you after updating to 0.0.6.5

Still crashes on 0.0.6.5
Also discovered that upon applying any glamour with OMG, my weapon mods (unaffected by glamourer) stop working.
To clarify,
1. Have modded axe in Penumbra
2. Apply preset with Glamourer which does not affect the mainhand slot
3. vanilla axe now displays.
This behaviour does not occur when setting the same preset with Glamourer itself. Though a different issue I believe the cause to be related to this one.

**Comment by PayneZA** [comment]
Thankyou for your submissions, thought I'd just update.

I haven't been able to cause a crash on my end when generating previews / outfits, with regards to glamour applying the way it does it is the same as going in chat.

/glamour apply DESIGN|<me> 

So that's as much control as I have when applying a design.

It will always be a best effort service, since I have zero communication with penumbra / glamourer dev's and very little time, one thing I can say in my design usage there are 0 weapon mods and all designs in glamourer are saved without customizations.

I wish I had a better answer to give but that's all I can until I can have it happen to me.

**Comment by Lunatory** [comment]
Hi, thanks for the followup. I no longer have either issue, still on version 0.0.6.5. I guess a recent Glamourer update fixed it?
